name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn -B package --file pom.xml || { echo "Maven build failed"; cat target/surefire-reports/*.txt; exit 1; }

      - name: Debug Directory Structure
        run: ls -R

      - name: Check JAR Existence
        run: |
          if [ -f "target/securelend-backend-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR found!"
          else
            echo "JAR not found!"
            exit 1
          fi

      - name: Copy JAR to Terraform directory
        run: cp target/securelend-backend-0.0.1-SNAPSHOT.jar terraform/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var "jwt_secret=${{ secrets.JWT_SECRET }}"

      - name: Output App URL
        working-directory: ./terraform
        run: terraform output app_url